import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import {getSession} from "next-auth/react";
import Login from "@/components/Login";
import Feed from "@/components/Feed";
import RightSidebar from "@/components/RightSidebar";

// const inter = Inter({ subsets: ['latin'] })

export default function Home({session}) {
    if (!session) return <Login/>;
    return (
        <div>
            <Head>
                <title>Northeastern Social Network</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <main class="flex bg-gray-100">
                <Sidebar/>
                <Feed/>
                <RightSidebar/>
            </main>
        </div>
    )
}


export async function getServerSideProps(context) {
    const session = await getSession(context);
    return {
        props: {
            session,
        },
    };
}